export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'
export const ADD_ITEM='ADD_ITEM'
export const RETURN_ITEMS='RETURN_ITEMS'
export const CHANGE_USER = 'CHANGE_USER'
export const CHANGE_USER_ERROR = 'CHANGE_USER_ERROR'

